# Site settings
title: BootingE's Engineering Blog
email: bootinge@gmail.com
description: "BootingE's Engineering Blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bootinge.github.io" # the base hostname & protocol for your site
github_username:  bootinge

# Build settings
#markdown: kramdown

permalink: pretty

markdown:     redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap
